### ISSUE TITLE
问下您在lrn/doc/code/model.py这里文件里是不是做了bert嵌入和其他特征向量的拼接？

### ISSUE THREAD

**Issue by zysNLP** [bzhangGo/lrn#1]
如题

**Comment by bzhangGo** [comment]
Hi,
原则上是可以的，请参见：
https://github.com/bzhangGo/lrn/blob/master/doc/code/model.py#L274
https://github.com/bzhangGo/lrn/blob/master/doc/code/model.py#L112

可以通过参数enable_bert调整。不过在我们的实验里没有使用。Doc分类的数据集蛮大的，采用BERT训练时间会非常长。

**Comment by zysNLP** [comment]
如果忽略使用DOC分类这种大型数据集，我的意思是，想知道拼接的做法是怎样的，例如我有1000条句子作为训练数据，进行bert微调时，怎么把例如“句子长度”、“句子中名词数量”这类特征加进去？

**Comment by bzhangGo** [comment]
我不太清楚你的具体任务，可能在想法上有所不同。

根据你说的，”句子长度，句子中名词数量“这类应该属于句子级别的特征，而不是词级别的特征。一种做法是依据你定义的规则提取句子特征向量 x=[句子长度，句子名词数量，...]（可以使用一些特征正则的方法），然后将其拼接到Neural Model的句子表示上面，比如 concat[feature; x] https://github.com/bzhangGo/lrn/blob/master/doc/code/model.py#L237。

**Comment by zysNLP** [comment]
我的意思是，在bert的run_classifier.py中的create_model里，output_layer的输出维度就是[batch_size, hidden_size]，而我的句子特征就是[batch_size, n]， n=特征个数，我是查到可以concat的，就是不知道具体怎么操作的。任务是文本分类或者NLI等都可以。

**Comment by bzhangGo** [comment]
如果是tensorflow的话，大致会有这个几个流程：
1. 读取数据的时候，提取特征向量，比如是个list列表 (https://github.com/bzhangGo/lrn/blob/master/doc/code/data.py#L84)
2. 转化成基于numpy的batch(https://github.com/bzhangGo/lrn/blob/master/doc/code/data.py#L149)
3. 定义tensorflow特征变量 (https://github.com/bzhangGo/lrn/blob/master/doc/code/main.py#L99)
4. 拼接特征：tf.concat([feature, x], axis=-1)

**Comment by zysNLP** [comment]
这个步骤没错，问题是bert想在create_model函数这里拼接的话，因为训练数据每次来batch_size个，所以每次需要传入相应个数的其他特征进行你的这个操作，我就是每次传的这个过程实现不了。因为这个函数没有变量能控制batchsize的大小

**Comment by bzhangGo** [comment]
操作的原理应该是一样的，你说的create_model应该会涉及tfrecord之类的特征修改。

我的代码里对bert的操作进行了包装，所以操作起来会随意一些。对run_classifier，我没怎么跑过这个代码，给不了你太多帮助。
